HOST: http://api.nutraspace.com/v1/

--- User API v2 ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
User
Operations related to managing users and profiles
--
Get user by user name
GET /user/{username}
< 200
< Content-Type: application/json
{   
    username: "mmarshall",
    emails: ["mateomm86@yahoo.com", "mmarshall@nutraspace.com"],
    first_name: "Matthew",
    middle_name: "Magee",
    last_name: "Marshall",
    gender: "male",
    locale: "en-US",
    age: 26,
    timezone: -5
}

Create a new user with username and password
POST /user
> Content-Type: application/json
{ "username":"mmarshall", "password": "jellyfish" }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/v1/user/mmarshall" }

Update a user profile
PUT /user/{username}
> Content-Type: application/json
{
    "edu_level": "bachelors",
    "edu_institution": "MIT"
}
< 201
< Content_type: application/json
{
    "status": "updated",
    "url": "/v1/user/mmarshall",
    "fields": [
        "edu_level",
        "edu_institution"
    ]
}

--
Group
Operations related to managing groups and group memberships
--
Create a new group
POST /group
{
    "realm": "nutraspace.com",
    "name": "Dietitians",
    "description": "A place for dietitians to congregate",
    "admins": [
        "mmarshall",
        "akannan"
    ]
}
< 201
{ "status": "created", "url": "/v1/group/032342-2432-4234-908" }