HOST: http://api.nutraspace.com/v1/

--- User API v2 ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
User Resources
The following is a section of resources related to the user domain
--
Get user by user name or ID
GET /user/{id}
< 200
< Content-Type: application/json
{   
    username: "mmarshall",
    emails: ["mateomm86@yahoo.com", "mmarshall@nutraspace.com"],
    first_name: "Matthew",
    middle_name: "Magee",
    last_name: "Marshall",
    gender: "male",
    locale: "en-US",
    age: 26,
    timezone: -5
}

Create a new user with username and password
POST /user
> Content-Type: application/json
{ "username":"mmarshall", "password": "jellyfish" }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/user/mmarshall" }

-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }